// <auto-generated />
using Dynamic_Sentence_Web_App.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dynamic_Sentence_Web_App.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220812232709_InitialiseTables")]
    partial class InitialiseTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dynamic_Sentence_Web_App.Models.Sentence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Sentence");
                });

            modelBuilder.Entity("Dynamic_Sentence_Web_App.Models.WordSentence", b =>
                {
                    b.Property<int>("WordUnitId")
                        .HasColumnType("int");

                    b.Property<int>("SentenceId")
                        .HasColumnType("int");

                    b.HasKey("WordUnitId", "SentenceId");

                    b.HasIndex("SentenceId");

                    b.ToTable("WordSentence");
                });

            modelBuilder.Entity("Dynamic_Sentence_Web_App.Models.WordType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WordType");
                });

            modelBuilder.Entity("Dynamic_Sentence_Web_App.Models.WordUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Word")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WordTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WordTypeId");

                    b.ToTable("WordUnit");
                });

            modelBuilder.Entity("Dynamic_Sentence_Web_App.Models.WordSentence", b =>
                {
                    b.HasOne("Dynamic_Sentence_Web_App.Models.Sentence", "Sentence")
                        .WithMany("WordSentences")
                        .HasForeignKey("SentenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dynamic_Sentence_Web_App.Models.WordUnit", "WordUnit")
                        .WithMany("WordSentences")
                        .HasForeignKey("WordUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dynamic_Sentence_Web_App.Models.WordUnit", b =>
                {
                    b.HasOne("Dynamic_Sentence_Web_App.Models.WordType", "WordType")
                        .WithMany()
                        .HasForeignKey("WordTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
